### ISSUE TITLE
How run it?

### ISSUE THREAD

**Issue by umaruu02** [mustafaaljadery/gemma-2B-10M#3]
I don't quite understand how to install and run it. 
I downloaded this folder from github, and downloaded all 13 files from hugging face. What's next, in which folder should I put them and how to run them?

**Comment by AdaptiveStep** [comment]
Do we have any examples at all? 
Has anyone confirmed if its useful?

**Comment by susanin1970** [comment]
I cloned repo, installed dependencies from requirements and tried to run main script `python -m src.main` from root folder of repo  
And I got this error: 
```
Traceback (most recent call last):
  File "/sdb/repositories/gemma-2B-10M/src/main.py", line 37, in <module>
    tokenizer = AutoTokenizer.from_pretrained(model_path)
  File "/home/reutov/.local/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 828, in from_pretrained
    config = AutoConfig.from_pretrained(
  File "/home/reutov/.local/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 930, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/reutov/.local/lib/python3.10/site-packages/transformers/configuration_utils.py", line 631, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/reutov/.local/lib/python3.10/site-packages/transformers/configuration_utils.py", line 686, in _get_config_dict
    resolved_config_file = cached_file(
  File "/home/reutov/.local/lib/python3.10/site-packages/transformers/utils/hub.py", line 370, in cached_file
    raise EnvironmentError(
OSError: ./models/models--mustafaaljadery--gemma-2B-10M does not appear to have a file named config.json. Checkout 'https://huggingface.co/./models/models--mustafaaljadery--gemma-2B-10M/tree/None' for available files.
```  

What am I doing wrong? Thanks fo answer in advance :)
